### ISSUE TITLE
Bug in saving / loading json with new adaptive error rate features

### ISSUE THREAD

**Issue by DM-Berger** [stfxecutables/df-analyze#51]
**Describe the bug**
```
    @staticmethod
    def from_json(root: Path) -> ProgramOptions:
        def is_jsonpickle_dict(value: Any) -> bool:
            return isinstance(value, dict) and "__objclass__" in value
    
        def to_enum(d: dict) -> Enum:
            enum = d["__objclass__"]
            return enum(d["_value_"])
    
        def is_path(d: dict) -> bool:
            return isinstance(d, dict) and "_raw_paths" in d
    
        def to_path(d: dict) -> Enum:
            return Path(d["_raw_paths"][0])
    
        options = root / "options.json"
        obj = cast(dict, jsonpickle.decode(options.read_text()))
>       obj.pop("version", None)
        ^^^^^^^
E       AttributeError: 'ProgramOptions' object has no attribute 'pop'

src/df_analyze/cli/cli.py:597: AttributeError
=================================================================================================================== short test summary info ====================================================================================================================
FAILED test/test_saving.py::test_json[cps_85_wages] - AttributeError: 'ProgramOptions' object has no attribute 'pop'
FAILED test/test_saving.py::test_json[water-treatment] - AttributeError: 'ProgramOptions' object has no attribute 'pop'
FAILED test/test_saving.py::test_json[jungle_chess_2pcs_endgame_rat_panther] - AttributeError: 'ProgramOptions' object has no attribute 'pop'
FAILED test/test_saving.py::test_json[abalone] - AttributeError: 'ProgramOptions' object has no attribute 'pop'
```

**Desktop (please complete the following information):**

MacOS Applie Silicon M2

**Additional context**

Most likely this is non-crucial, but I am logging it here for future reference after merging the adaptive error rate changes.
